#!/usr/bin/env bash

export OO_DS_RABBITMQ_URL="${OO_DS_RABBITMQ_URL:-""}"

## Parse databases URL:

REDIS_HOST="$( echo "${SCALINGO_REDIS_URL}" \
	| cut -d "@" -f2 | cut -d ":" -f1 )"

REDIS_PORT="$( echo "${SCALINGO_REDIS_URL}" \
	| cut -d ":" -f4 | cut -d "/" -f1 )"

OO_DS_SERVICES_COAUTHORING_REDIS_HOST="${OO_DS_SERVICES_COAUTHORING_REDIS_HOST:-"${REDIS_HOST:-""}"}"
OO_DS_SERVICES_COAUTHORING_REDIS_PORT="${OO_DS_SERVICES_COAUTHORING_REDIS_PORT:-"${REDIS_PORT:-""}"}"

export OO_DS_SERVICES_COAUTHORING_REDIS_HOST
export OO_DS_SERVICES_COAUTHORING_REDIS_PORT


OO_DS_SERVICES_COAUTHORING_SQL_TYPE="postgresql"

POSTGRESQL_HOST="$( echo "${SCALINGO_POSTGRESQL_URL}" \
	| cut -d "@" -f2 | cut -d ":" -f1 )"

POSTGRESQL_USER="$( echo "${SCALINGO_POSTGRESQL_URL}" \
	| cut -d "/" -f3 | cut -d ":" -f1 )"

POSTGRESQL_PORT="$( echo "${SCALINGO_POSTGRESQL_URL}" \
	| cut -d ":" -f4 | cut -d "/" -f1 )"

POSTGRESQL_PASS="$( echo "${SCALINGO_POSTGRESQL_URL}" \
	| cut -d "@" -f1 | cut -d ":" -f3 )"

POSTGRESQL_DBNAME="$( echo "${SCALINGO_POSTGRESQL_URL}" \
	| cut -d "?" -f1 | cut -d "/" -f4 )"

OO_DS_SERVICES_COAUTHORING_SQL_DBHOST="${OO_DS_SERVICES_COAUTHORING_SQL_DBHOST:-"${POSTGRESQL_HOST:-""}"}"
OO_DS_SERVICES_COAUTHORING_SQL_DBPORT="${OO_DS_SERVICES_COAUTHORING_SQL_DBPORT:-"${POSTGRESQL_PORT:-""}"}"
OO_DS_SERVICES_COAUTHORING_SQL_DBUSER="${OO_DS_SERVICES_COAUTHORING_SQL_DBUSER:-"${POSTGRESQL_USER:-""}"}"
OO_DS_SERVICES_COAUTHORING_SQL_DBPASS="${OO_DS_SERVICES_COAUTHORING_SQL_DBPASS:-"${POSTGRESQL_PASS:-""}"}"
OO_DS_SERVICES_COAUTHORING_SQL_DBNAME="${OO_DS_SERVICES_COAUTHORING_SQL_DBNAME:-"${POSTGRESQL_DBNAME:-""}"}"

export OO_DS_SERVICES_COAUTHORING_SQL_DBTYPE
export OO_DS_SERVICES_COAUTHORING_SQL_DBHOST
export OO_DS_SERVICES_COAUTHORING_SQL_DBPORT
export OO_DS_SERVICES_COAUTHORING_SQL_DBUSER
export OO_DS_SERVICES_COAUTHORING_SQL_DBPASS
export OO_DS_SERVICES_COAUTHORING_SQL_DBNAME


NODE_CONFIG_DIR="/app/config"
export NODE_CONFIG_DIR

NODE_ENV="${NODE_ENV:-"production"}"
export NODE_ENV

LD_LIBRARY_PATH="/app/server/FileConverter/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export LD_LIBRARY_PATH


# S3 storage settings
OO_S3_ENDPOINT="${OO_S3_ENDPOINT:-"${S3_ENDPOINT:-""}"}"
OO_S3_REGION="${OO_S3_REGION:-"${S3_REGION:-""}"}"
OO_S3_BUCKET_NAME="${OO_S3_BUCKET_NAME:-"${S3_BUCKET:-""}"}"
OO_S3_STORAGE_FOLDER_NAME="${OO_S3_STORAGE_FOLDER_NAME:-"onlyoffice"}"
OO_S3_USE_PATH_STYLE="${OO_S3_USE_PATH_STYLE:-"false"}"
OO_S3_ACCESS_KEY_ID="${OO_S3_ACCESS_KEY_ID:-"${S3_ACCESS_KEY_ID:-""}"}"
OO_S3_SECRET_ACCESS_KEY="${OO_S3_SECRET_ACCESS_KEY:-"${S3_SECRET_ACCESS_KEY:-""}"}"

export OO_S3_ENDPOINT
export OO_S3_REGION
export OO_S3_BUCKET_NAME
export OO_S3_STORAGE_FOLDER_NAME
export OO_S3_USE_PATH_STYLE
export OO_S3_ACCESS_KEY_ID
export OO_S3_SECRET_ACCESS_KEY
